# This script compares the moves generated by stockfish
# and the moves generated by our engine and produces debugging
# information if we generated some wrong moves.

# Stockfish gives input in the form
# <Move>: <Count> (e.g. e2e4: 1)
# This function removes the count and returns the move.
def clean(move):
    cleaned_move = move.split(":", 1)[0]
    return cleaned_move

# Firstly take in our moves
Our_Moves = []
for _ in range(int(input())):
  Our_Moves.append(clean(input()))

# Then take in the moves from stockfish
Stockfish_Moves = []
for _ in range(int(input())):
  Stockfish_Moves.append(clean(input()))

Our_Moves.sort()
Stockfish_Moves.sort()

if Our_Moves == Stockfish_Moves: print("Correct moves generated")

# Give information based on the moves we are missing
# or the moves we have generated that are illegal
else:
  print("Incorrect moves generated")
  Our_Moves       = set(Our_Moves)
  Stockfish_Moves = set(Stockfish_Moves)

  if len(Our_Moves) > len(Stockfish_Moves):
    print("The following moves are illegal:")

    for move in (Our_Moves - Stockfish_Moves): print(move)

  else:
    print("We didn't generate the following moves:")

    for move in (Stockfish_Moves - Our_Moves): print(move)
